export const PAYSTACK_BANKS = [
	{ name: 'Abbey Mortgage Bank', code: '801', currency: 'NGN', id: 174 },
	{ name: 'Access Bank', code: '044', currency: 'NGN', id: 1 },
	{ name: 'Access Bank (Diamond)', code: '063', currency: 'NGN', id: 3 },
	{ name: 'ALAT by WEMA', code: '035A', currency: 'NGN', id: 27 },
	{ name: 'Amju Unique MFB', code: '50926', currency: 'NGN', id: 179 },
	{ name: 'ASO Savings and Loans', code: '401', currency: 'NGN', id: 63 },
	{ name: 'Bainescredit MFB', code: '51229', currency: 'NGN', id: 181 },
	{ name: 'Bowen Microfinance Bank', code: '50931', currency: 'NGN', id: 108 },
	{ name: 'Carbon', code: '565', currency: 'NGN', id: 82 },
	{ name: 'CEMCS Microfinance Bank', code: '50823', currency: 'NGN', id: 74 },
	{ name: 'Citibank Nigeria', code: '023', currency: 'NGN', id: 2 },
	{ name: 'Coronation Merchant Bank', code: '559', currency: 'NGN', id: 173 },
	{ name: 'Ecobank Nigeria', code: '050', currency: 'NGN', id: 4 },
	{ name: 'Ekondo Microfinance Bank', code: '562', currency: 'NGN', id: 64 },
	{ name: 'Eyowo', code: '50126', currency: 'NGN', id: 167 },
	{ name: 'Fidelity Bank', code: '070', currency: 'NGN', id: 6 },
	{ name: 'Firmus MFB', code: '51314', currency: 'NGN', id: 177 },
	{ name: 'First Bank of Nigeria', code: '011', currency: 'NGN', id: 7 },
	{ name: 'First City Monument Bank', code: '214', currency: 'NGN', id: 8 },
	{ name: 'FSDH Merchant Bank Limited', code: '501', currency: 'NGN', id: 112 },
	{ name: 'Globus Bank', code: '00103', currency: 'NGN', id: 70 },
	{ name: 'GoMoney', code: '100022', currency: 'NGN', id: 183 },
	{ name: 'Guaranty Trust Bank', code: '058', currency: 'NGN', id: 9 },
	{ name: 'Hackman Microfinance Bank', code: '51251', currency: 'NGN', id: 111 },
	{ name: 'Hasal Microfinance Bank', code: '50383', currency: 'NGN', id: 81 },
	{ name: 'Heritage Bank', code: '030', currency: 'NGN', id: 10 },
	{ name: 'Ibile Microfinance Bank', code: '51244', currency: 'NGN', id: 168 },
	{ name: 'Infinity MFB', code: '50457', currency: 'NGN', id: 172 },
	{ name: 'Jaiz Bank', code: '301', currency: 'NGN', id: 22 },
	{ name: 'Keystone Bank', code: '082', currency: 'NGN', id: 11 },
	{ name: 'Kredi Money MFB LTD', code: '50200', currency: 'NGN', id: 184 },
	{ name: 'Kuda Bank', code: '50211', currency: 'NGN', id: 67 },
	{ name: 'Lagos Building Investment Company Plc.', code: '90052', currency: 'NGN', id: 109 },
	{ name: 'Links MFB', code: '50549', currency: 'NGN', id: 180 },
	{ name: 'Mayfair MFB', code: '50563', currency: 'NGN', id: 175 },
	{ name: 'Mint MFB', code: '50304', currency: 'NGN', id: 178 },
	{ name: 'Paga', code: '100002', currency: 'NGN', id: 185 },
	{ name: 'PalmPay', code: '999991', currency: 'NGN', id: 169 },
	{ name: 'Parallex Bank', code: '526', currency: 'NGN', id: 26 },
	{ name: 'Parkway - ReadyCash', code: '311', currency: 'NGN', id: 110 },
	{ name: 'Paycom', code: '999992', currency: 'NGN', id: 171 },
	{ name: 'Petra Mircofinance Bank Plc', code: '50746', currency: 'NGN', id: 170 },
	{ name: 'Polaris Bank', code: '076', currency: 'NGN', id: 13 },
	{ name: 'Providus Bank', code: '101', currency: 'NGN', id: 25 },
	{ name: 'Rand Merchant Bank', code: '502', currency: 'NGN', id: 176 },
	{ name: 'Rubies MFB', code: '125', currency: 'NGN', id: 69 },
	{ name: 'Sparkle Microfinance Bank', code: '51310', currency: 'NGN', id: 72 },
	{ name: 'Stanbic IBTC Bank', code: '221', currency: 'NGN', id: 14 },
	{ name: 'Standard Chartered Bank', code: '068', currency: 'NGN', id: 15 },
	{ name: 'Sterling Bank', code: '232', currency: 'NGN', id: 16 },
	{ name: 'Suntrust Bank', code: '100', currency: 'NGN', id: 23 },
	{ name: 'TAJ Bank', code: '302', currency: 'NGN', id: 68 },
	{ name: 'TCF MFB', code: '51211', currency: 'NGN', id: 75 },
	{ name: 'Titan Bank', code: '102', currency: 'NGN', id: 73 },
	{ name: 'Union Bank of Nigeria', code: '032', currency: 'NGN', id: 17 },
	{ name: 'United Bank For Africa', code: '033', currency: 'NGN', id: 18 },
	{ name: 'Unity Bank', code: '215', currency: 'NGN', id: 19 },
	{ name: 'VFD Microfinance Bank Limited', code: '566', currency: 'NGN', id: 71 },
	{ name: 'Wema Bank', code: '035', currency: 'NGN', id: 20 },
	{ name: 'Zenith Bank', code: '057', currency: 'NGN', id: 21 },
];

export const GET_PAYSTACK_BANKS_AS_OPTIONS = () =>
	PAYSTACK_BANKS.map(({ name, code }) => (
		<option value={code} key={code}>
			{name}
		</option>
	));
